

List<dynamic> walletData = [
  {
    "image":'assets/images/gift-card.png',
    "headline":'Gift card wallet',
    "subtitle":'',
    "score":'5353',
    "withdraw":'',
    "transMoney":'',
    "tHistory":'Transaction History',
    "redeemButton":'Redeem gift card',
    "waitOrder":'',
    "confOrder": '',
    "lifeMagicCoinText":'',
    "lifeMagicCoin":'',
  },
  {
    "image":'assets/images/rupees.png',
    "headline":'Lifeline card wallet',
    "subtitle":'Upcomming EMI/Udhar : 4356',
    "score":'3562',
    "withdraw":'Withdraw',
    "transMoney":'Transfer Money',
    "tHistory":'Transaction History',
    "redeemButton":'',
    "waitOrder":'',
    "confOrder": '',
    "lifeMagicCoinText":'',
    "lifeMagicCoin":'',
  },
  {
    "image":'assets/images/hold.png',
    "headline":'Hold Wallet',
    "subtitle":'',
    "score":'562',
    "withdraw":'',
    "transMoney":'',
    "tHistory":'Transaction History',
    "redeemButton":'',
    "waitOrder":'2 order waiting conformation',
    "confOrder": '',
    "lifeMagicCoinText":'',
    "lifeMagicCoin":'',
  },
  {
    "image":'assets/images/lifeline.jpg',
    "headline":'Lifeline Coin',
    "subtitle":'',
    "score":'3562',
    "withdraw":'',
    "transMoney":'',
    "tHistory":'Transaction History',
    "redeemButton":'',
    "waitOrder":'',
    "confOrder": '11 Sep 2023 To 11 Oct 2023',
    "lifeMagicCoinText":'Lifeline Magic Coin',
    "lifeMagicCoin":'600',
  },
  {
    "image":'assets/images/king.png',
    "headline":'CashBack Coin',
    "subtitle":'Add credit coin',
    "score":'3562',
    "withdraw":'',
    "transMoney":'',
    "tHistory":'Transaction History',
    "redeemButton":'',
    "waitOrder":'',
    "confOrder": '11 Sep 2023 To 11 Oct 2023',
    "lifeMagicCoinText":'',
    "lifeMagicCoin":'',
  },
];